spring:
  application:
    name: cloud-errands-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/cloud-errends/cloud-errands-cloud-config
          search-paths: respo
          username: iamchriswu
          password: 1172477133wq
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/